[package]
name = "anathema-value-resolver2"
edition.workspace = true
version.workspace = true
documentation = "https://togglebyte.github.io/anathema-guide/"
homepage = "https://github.com/togglebyte/anathema"
repository = "https://github.com/togglebyte/anathema"

[dependencies]
anathema-state = { workspace = true }
anathema-templates = { workspace = true }
anathema-store = { workspace = true }
puffin = { version = "0.19.1", features = ["web"], optional = true }
puffin_http = { version = "0.16.1", optional = true }

[features]
default = []
profile = ["puffin", "puffin_http"]

[lints]
workspace = true
