[package]
name = "anathema-frontend"
edition.workspace = true
version.workspace = true

[dependencies]
anathema-compiler = { workspace = true }
anathema-geometry = { workspace = true }
anathema-hashmap = { workspace = true }
anathema-store = { workspace = true }
arrayvec = "0.7.6"
bitflags = { workspace = true }
compact_str = { workspace = true }
crossterm = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }

[lints]
workspace = true
