[package]
name = "anathema-debug"
license = "MIT"
description = "Debug utils for Anathema"
version.workspace = true
edition.workspace = true

[dependencies]

[features]
default = []
filelog = []

[lints]
workspace = true
