[package]
name = "anathema-state"
license = "MIT"
description = "Anathema state and value types"
version.workspace = true
edition.workspace = true

[dependencies]
anathema-debug = { path = "../anathema-debug", version = "0.2.1" }
anathema-state-derive = { path = "../anathema-state-derive", version = "0.2.1" }
anathema-store = { path = "../anathema-store", version = "0.2.1" }

[lints]
workspace = true
