[package]
name = "anathema-widgets"
edition.workspace = true
version.workspace = true

[dependencies]
anathema-geometry = { path = "../anathema-geometry", version = "0.2.12-beta" }
anathema-frontend = { path = "../anathema-frontend", version = "0.2.12-beta" }
anathema-runtime = { path = "../anathema-runtime", version = "0.2.12-beta" }

[lints]
workspace = true
