[package]
name = "anathema-runtime"
license = "MIT"
description = "Anathema runtime and value types"
version.workspace = true
edition.workspace = true
documentation = "https://togglebyte.github.io/anathema-guide/"
homepage = "https://github.com/togglebyte/anathema"
repository = "https://github.com/togglebyte/anathema"

[dependencies]
anathema-compiler = { workspace = true }
anathema-geometry = { workspace = true }
anathema-hashmap = { workspace = true }
anathema-state-derive = { workspace = true }
anathema-store = { workspace = true }
parking_lot = "0.12.5"

[features]
default = []
multithread = []

[lints]
workspace = true
