[package]
name = "testutils"
license = "MIT"
description = "Test utilities for Anathema"
version.workspace = true
edition.workspace = true

[dependencies]
anathema = { path = "../", version = "0.2.1" }

[lints]
workspace = true
