[package]
name = "anathema-compiler"
edition.workspace = true
version.workspace = true

[dependencies]
anathema-store = { path = "../anathema-store", version = "0.2.12-beta" }
serde = { version = "1.0.228", features = ["derive"], optional = true }
nohash-hasher = { workspace = true }

[features]
default = []
serde = ["dep:serde"]

[lints]
workspace = true
