[package]
name = "anathema-core"
edition.workspace = true
version.workspace = true

[dependencies]
anathema-store = { path = "../anathema-store", version = "0.2.12-beta" }
anathema-geometry = { path = "../anathema-geometry", version = "0.2.12-beta" }
anathema-runtime = { path = "../anathema-runtime", version = "0.2.12-beta" }

[lints]
workspace = true

[features]
default = []
multithread = []

