[package]
name = "anathema-store"
license = "MIT"
description = "Various storage types for Anathema"
version.workspace = true
edition.workspace = true

[dependencies]
anathema-debug = { path = "../anathema-debug", version = "0.2.1" }

[lints]
workspace = true
