[package]
name = "anathema-default-widgets"
version.workspace = true
edition.workspace = true

[dependencies]
anathema-backend = { path = "../anathema-backend" }
anathema-geometry = { path = "../anathema-geometry" }
anathema-state = { path = "../anathema-state" }
anathema-store = { path = "../anathema-store" }
anathema-templates = { path = "../anathema-templates" }
anathema-value-resolver = { path = "../anathema-value-resolver" }
anathema-widgets = { path = "../anathema-widgets" }
bitflags = { workspace = true }
unicode-width = { workspace = true }

[lints]
workspace = true
